// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD2_4OP4B1rgKNgSF-2_39H29fVIF6fPM',
    appId: '1:783228202117:web:d138276e087f56ecc60dec',
    messagingSenderId: '783228202117',
    projectId: 'daftarbelanja-e9f7e',
    authDomain: 'daftarbelanja-e9f7e.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-e9f7e-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-e9f7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBliOaDGm5fB7zC0ILtWDpxgig6QbjVIgM',
    appId: '1:783228202117:android:2e363d392ef81814c60dec',
    messagingSenderId: '783228202117',
    projectId: 'daftarbelanja-e9f7e',
    databaseURL: 'https://daftarbelanja-e9f7e-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-e9f7e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD2_4OP4B1rgKNgSF-2_39H29fVIF6fPM',
    appId: '1:783228202117:web:93b89cc5b1c4325dc60dec',
    messagingSenderId: '783228202117',
    projectId: 'daftarbelanja-e9f7e',
    authDomain: 'daftarbelanja-e9f7e.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-e9f7e-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-e9f7e.firebasestorage.app',
  );
}
