// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFj2wDmRG_4iJ2qM3ReDzSaJmcIatYUp0',
    appId: '1:683290115407:web:29c90e6d46400211aad93a',
    messagingSenderId: '683290115407',
    projectId: 'latihan-c5e2b',
    authDomain: 'latihan-c5e2b.firebaseapp.com',
    databaseURL: 'https://latihan-c5e2b-default-rtdb.firebaseio.com',
    storageBucket: 'latihan-c5e2b.firebasestorage.app',
    measurementId: 'G-2HSQZBKRRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSGIbKh55bn7ugQ43lJSfIY51dooGOmsw',
    appId: '1:683290115407:android:b361b72d865dfe85aad93a',
    messagingSenderId: '683290115407',
    projectId: 'latihan-c5e2b',
    databaseURL: 'https://latihan-c5e2b-default-rtdb.firebaseio.com',
    storageBucket: 'latihan-c5e2b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFj2wDmRG_4iJ2qM3ReDzSaJmcIatYUp0',
    appId: '1:683290115407:web:887e00d0dfdcb209aad93a',
    messagingSenderId: '683290115407',
    projectId: 'latihan-c5e2b',
    authDomain: 'latihan-c5e2b.firebaseapp.com',
    databaseURL: 'https://latihan-c5e2b-default-rtdb.firebaseio.com',
    storageBucket: 'latihan-c5e2b.firebasestorage.app',
    measurementId: 'G-KQ7TWTSHTP',
  );
}
